### PR TITLE
Add useScrollIntoViewHook

### PR DESCRIPTION
**Pull request by phanlyhuynh**
@Rajdeepc https://github.com/Rajdeepc/hooks-collection/issues/8. I added useScrollIntoViewHook. Please check for me! Thanks!

### CODE REVIEW

**Comment by phanlyhuynh** [comment]
@Rajdeepc hi. Can you check for me? and it's look good, you can add "hacktoberfest-accepted" labels. Thanks~

**Comment by Rajdeepc** [comment]
@phanlyhuynh  Can you update the README.md also.

**Comment by phanlyhuynh** [comment]
@Rajdeepc yes. i updated.

**Review by Rajdeepc — APPROVED** [review]
Thanks for your PR.

**Pull request merged**
